version: '2.4'

services:
  nextjs:
    image: node:16-alpine
    command: npm run dev-head

    environment:
      NODE_ENV: "development"
      PORT: 3000

    ports:
      - 3000:3000

    working_dir: /src
    volumes:
      - ./:/src

    depends_on:
      contember:
        condition: service_started
      contember-migrations:
        condition: service_completed_successfully

  admin:
    image: node:16-alpine
    command: npm run start-admin
    user: '1000:1000'

    environment:
      VITE_PORT: '1480'
      VITE_CONTEMBER_ADMIN_API_BASE_URL: 'http://localhost:1481'
      VITE_CONTEMBER_ADMIN_SESSION_TOKEN: '0000000000000000000000000000000000000000'
      VITE_CONTEMBER_ADMIN_PROJECT_NAME: 'headless-cms'
      VITE_CONTEMBER_ADMIN_WEB_URL: 'http://localhost:3000'

    ports:
      - '1480:1480' # ports must match

    working_dir: /src
    volumes:
      - ./:/src:cached

  contember:
    image: contember/engine:1.0.0-alpha.1
    restart: on-failure

    environment:
      NODE_ENV: 'development'

      CONTEMBER_ROOT_EMAIL: 'contember@localhost'
      CONTEMBER_ROOT_PASSWORD: 'contember'
      CONTEMBER_ROOT_TOKEN: '0000000000000000000000000000000000000000'
      CONTEMBER_LOGIN_TOKEN: '1111111111111111111111111111111111111111'
      CONTEMBER_CONFIG_YAML: |
        projectDefaults:
          s3:
            prefix: '%project.slug%'

      DEFAULT_DB_HOST: 'postgres'
      DEFAULT_DB_PORT: '5432'
      DEFAULT_DB_USER: 'contember'
      DEFAULT_DB_PASSWORD: 'contember'

      DEFAULT_S3_ENDPOINT: 'http://localhost:1483'
      DEFAULT_S3_BUCKET: 'contember'
      DEFAULT_S3_REGION: ''
      DEFAULT_S3_KEY: 'contember'
      DEFAULT_S3_SECRET: 'contember'
      DEFAULT_S3_PROVIDER: 'minio'

      TENANT_DB_NAME: 'tenant'
      TENANT_MAILER_HOST: 'mailhog'
      TENANT_MAILER_PORT: '1025'
      TENANT_MAILER_FROM: 'contember@localhost'

    ports:
      - '1481:4000'

    depends_on:
      postgres:
        condition: service_healthy

  contember-cli:
    image: contember/cli:0.12.0-beta.2
    user: '1000:1000'

    environment:
      CONTEMBER_API_URL: 'http://contember:4000/'
      CONTEMBER_API_TOKEN: '0000000000000000000000000000000000000000'
      CONTEMBER_PROJECT_NAME: 'headless-cms'

    working_dir: /src
    volumes:
      - ./:/src:cached

    depends_on:
      contember:
        condition: service_started

  contember-migrations:
    image: contember/cli:0.12.0-beta.2
    command: 'migrations:execute . --yes'
    user: '1000:1000'

    environment:
      CONTEMBER_API_URL: 'http://contember:4000/'
      CONTEMBER_API_TOKEN: '0000000000000000000000000000000000000000'
      CONTEMBER_PROJECT_NAME: 'headless-cms'

    working_dir: /src
    volumes:
      - ./:/src:cached

    depends_on:
      contember:
        condition: service_started

  postgres:
    image: postgres:13-alpine

    environment:
      POSTGRES_PASSWORD: contember
      POSTGRES_USER: contember
      POSTGRES_DB: contember

    ports:
      - '1482:5432'

    volumes:
      - pgsql-data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U contember']
      interval: 5s
      timeout: 5s
      retries: 10

  s3:
    image: minio/minio
    entrypoint: /minio-entrypoint.sh
    command: 'server --address :1483 /data'

    environment:
      MINIO_ROOT_USER: contember
      MINIO_ROOT_PASSWORD: contember

    ports:
      - '1483:1483' # ports must match

    volumes:
      - s3-data:/data
      - ./scripts/minio/s3-policy.json:/bucket-policy.json
      - ./scripts/minio/s3-entrypoint.sh:/minio-entrypoint.sh

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1484:8025'

  adminer:
    image: adminer:4.8.0

    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: postgres
      ADMINER_DB: contember
      ADMINER_USERNAME: contember
      ADMINER_PASSWORD: contember
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Contember

    ports:
      - '1485:8080'

    depends_on:
      - postgres

volumes:
  pgsql-data: ~
  s3-data: ~
