# If you are using Mutagen on Mac, copy this override as docker-compose.override.yaml and run mutagen-compose up
version: '2.4'

services:
  nextjs:
    volumes:
      - code:/src

  admin:
    volumes:
      - code:/src:cached

  contember-cli:
    volumes:
      - code:/src:cached

  contember-migrations:
    volumes:
      - code:/src:cached

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "."
      beta: "volume://code"
      mode: "two-way-resolved"
      configurationBeta:
        permissions:
          defaultOwner: "id:1000"
          defaultGroup: "id:1000"